algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var

    resto: real

inicio

    n1 <- 10
    n2 <- 2
    resto <- n1 % n2
    escreval("resto = ", resto)
    leia (resto)

fimalgoritmo