algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var
    n1: inteiro
    n2: inteiro
    resto: real

inicio

    n1 <- 10
    n2 <- 2
    resto <- n1 % n2
    
     escreval("O resto da divisão é = ", resto)
    //leia (resto)

fimalgoritmo